apiVersion: v1
kind: Service
metadata:
  name: Standard Management
  labels:
    app: Standard Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Standard Management